apiVersion: v1
kind: Pod
metadata:
  name: echoweb
spec:
  containers:
  - name: echoweb
    image: jam13c/echoweb:1.0
    ports:
    - containerPort: 80
    env:
    - name: POD_ID
      valueFrom:
            fieldRef:
              fieldPath: metadata.name